apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cs16
  name: cs16
spec:
  type: LoadBalancer
  ports:
    - name: "27015"
      port: 27015
      protocol: UDP
      targetPort: 27015
  selector:
    io.kompose.service: cs16

