apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cs16
  name: cs16
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cs16
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: cs16
    spec:
      containers:
        - image: leandrosalvas/cs16
          name: cs16
          ports:
            - containerPort: 27015
              protocol: UDP
          volumeMounts:
            - mountPath: /home/cs16/cstrike/addons/amxmodx/configs/users.ini
              name: cs16-cm0
              subPath: users.ini
            - mountPath: /home/cs16/cstrike/motd.txt
              name: cs16-cm1
              subPath: motd.txt
            - mountPath: /home/cs16/cstrike/mapcycle.txt
              name: cs16-cm2
              subPath: mapcycle.txt
            - mountPath: /home/cs16/cstrike/server.cfg
              name: cs16-cm3
              subPath: server.cfg
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: users.ini
                path: users.ini
            name: cs16-cm0
          name: cs16-cm0
        - configMap:
            items:
              - key: motd.txt
                path: motd.txt
            name: cs16-cm1
          name: cs16-cm1
        - configMap:
            items:
              - key: mapcycle.txt
                path: mapcycle.txt
            name: cs16-cm2
          name: cs16-cm2
        - configMap:
            items:
              - key: server.cfg
                path: server.cfg
            name: cs16-cm3
          name: cs16-cm3
